enablePostgres: false

registry:
  host: digital-twin-registry.dev.ftcpro.co
  dataSource:
    ## The url, user, and password parameter will be ignored if 'enablePostgres' is set to true.
    ## In that case the postgresql auth parameters are used.
    url: jdbc:postgresql://ftcpro-postgresql-primary.postgres:5432/registry
    user: <path:digital-twin-registry/data/dev/database#user>
    password: <path:digital-twin-registry/data/dev/database#password>
  ingress:
    enabled: true
    tls: true
    urlPrefix: /semantics/registry
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
      nginx.ingress.kubernetes.io/x-forwarded-prefix: /semantics/registry
  resources:
    limits:
      cpu: 2
      memory: "1024Mi"
    requests:
      cpu: "10m"
      memory: "10Mi"
